name: Variables-And-Data-File-Example
on:
  pull_request:

jobs:
  variables-and-data-file-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: kamidana
        id: kamidana
        uses: ./
        with:
          template: testdata/variables-and-data-file-example.j2
          output_file: test.txt
          tee: true
          data_file: readme/replace-uses.json
          variables: |
            sample: test
            name: srz-zumix
      - run: |
          cat << EOS | tee output.txt
          ${{ steps.kamidana.outputs.text }}
          EOS
          diff output.txt test.txt
